# TODO replace `stevena` with unique prefix for naming/identifying your deployed resources
service: stevena-auth # AWS names API Gateway based on service name and does not like long names

# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  apiName: stevena-auth-gateway

functions:
  Returns200:
    handler: returns-200.handler
    events:
      - http:
          path: /
          method: get
          authorizer: aws_iam

resources:
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}